# Generated by Django 3.2 on 2021-04-15 19:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=600, validators=[django.core.validators.URLValidator()])),
                ('width', models.IntegerField(default=400)),
                ('height', models.IntegerField(default=400)),
                ('chart_type', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=999)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('site', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('eight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eight', to='quiz.program')),
                ('eleven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleven', to='quiz.program')),
                ('fifteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifteen', to='quiz.program')),
                ('five', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='five', to='quiz.program')),
                ('four', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='four', to='quiz.program')),
                ('fourteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourteen', to='quiz.program')),
                ('nine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nine', to='quiz.program')),
                ('one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one', to='quiz.program')),
                ('seven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seven', to='quiz.program')),
                ('six', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='six', to='quiz.program')),
                ('ten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ten', to='quiz.program')),
                ('thirteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thirteen', to='quiz.program')),
                ('three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three', to='quiz.program')),
                ('twelve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twelve', to='quiz.program')),
                ('two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two', to='quiz.program')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(max_length=5)),
                ('course', models.TextField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.program')),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('program_2', models.CharField(max_length=200)),
                ('comparison', models.TextField()),
                ('program_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='quiz.program')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_type', models.CharField(max_length=200)),
                ('career', models.TextField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.program')),
            ],
        ),
    ]
