# Generated by Django 3.1.7 on 2021-03-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('width', models.IntegerField(default=400)),
                ('height', models.IntegerField(default=400)),
                ('chart_type', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=999)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['key']},
        ),
        migrations.RemoveField(
            model_name='result',
            name='email',
        ),
    ]
