# Generated by Django 3.1.7 on 2021-03-15 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210315_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='url',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
