# Generated by Django 3.1.7 on 2021-03-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210315_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='program_2',
            field=models.CharField(max_length=200),
        ),
    ]
